# Generated by Django 5.0 on 2024-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_library_groups_library_is_active_library_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='Genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Human Development', 'Human development'), ('Romance', 'Romance'), ('Fiction', 'Fiction')], max_length=20, null=True),
        ),
    ]
