# Generated by Django 5.0.6 on 2024-06-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_library_phone_number_livre_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='Stock',
            field=models.IntegerField(default=1),
        ),
    ]
