# Generated by Django 5.0.6 on 2024-05-11 19:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('name_lib', models.CharField(max_length=60, unique=True)),
                ('groups', models.ManyToManyField(related_name='group_librairies', to='auth.permission')),
                ('user_permissions', models.ManyToManyField(related_name='user_libraries', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('Id_livre', models.AutoField(primary_key=True, serialize=False)),
                ('Name_book', models.CharField(default=None, max_length=50)),
                ('Authour_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Genre', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Stock', models.IntegerField()),
                ('Prix', models.FloatField(default=100)),
                ('Id_lib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.library')),
            ],
        ),
    ]
