# Generated by Django 5.0.6 on 2024-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
        migrations.AlterModelManagers(
            name='library',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='library',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='library',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='library',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='library',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='library',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='library',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='library',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='library',
            name='name_lib',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='library',
            name='password',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='library',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
