# Generated by Django 5.0.6 on 2024-05-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_alter_library_options_alter_library_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livre',
            table='Livre',
        ),
    ]
