# Generated by Django 5.0.6 on 2024-05-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_alter_livre_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='library',
            table='Library',
        ),
    ]
